# Generated by Django 5.1.5 on 2025-01-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_e_login', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
