# Generated by Django 5.1.5 on 2025-01-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_e_login", "0006_post_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
